import type { InnerPage } from "@/content/types";
import { routes } from "@/content/site";

export const specialtiesPage: InnerPage = {
  slug: "specialties",
  path: routes.specialties,
  meta: {
    title: "Medical Billing for Every Healthcare Specialty",
    description:
      "From solo family practice to multi-site hospital networks — Health Billing has specialty-trained billing teams for every type of provider. We know them all.",
  },
  hero: {
    breadcrumb: [{ label: "Home", href: routes.home }],
    title: ["Medical Billing for Every", "Healthcare Specialty"],
    lead: "From solo family practice to multi-site hospital networks — Health Billing has specialty-trained billing teams for every type of provider. Your specialty has unique codes, unique payer rules, and unique compliance requirements. We know them all.",
    stats: [
      { value: "40+", label: "Specialties covered" },
      { value: "4,800+", label: "Providers served" },
      { value: "Dedicated", label: "Specialty billing teams" },
      { value: "All 50", label: "States active" },
    ],
  },
  blocks: [
    {
      type: "cards",
      id: "primary-care",
      eyebrow: "Primary & Preventive Care",
      title: "The Front Line of Healthcare",
      columns: 2,
      variant: "default",
      items: [
        {
          id: "primary-care-internal-medicine",
          icon: "stethoscope",
          title: "Primary Care / Internal Medicine",
          body: "E&M coding optimization, Annual Wellness Visits, chronic care management (CCM), preventive services, and MIPS quality reporting.",
          bullets: [
            "E&M level optimization (99202–99215)",
            "Chronic Care Management (CCM) billing",
            "Annual Wellness Visit (AWV) codes",
            "Transitional Care Management (TCM)",
          ],
        },
        {
          id: "urgent-care",
          icon: "zap",
          title: "Urgent Care",
          body: "High-volume same-day billing, urgent care E&M coding, occupational health billing, and telehealth urgent care.",
          bullets: [
            "Urgent care facility fee billing (S9083)",
            "Same-day claim submission",
            "Occupational medicine and work injury",
            "Pre-employment physical billing",
          ],
        },
        {
          id: "pediatrics",
          icon: "baby",
          title: "Pediatrics",
          body: "Well-child visits, immunization billing, developmental screenings, and CHIP/Medicaid pediatric billing.",
          bullets: [
            "Well-child visit codes (99381–99395)",
            "Vaccine administration (90460/90461)",
            "EPSDT / developmental screening",
            "CHIP and pediatric Medicaid",
          ],
        },
        {
          id: "obgyn",
          icon: "flower",
          title: "OB/GYN & Women's Health",
          body: "Global OB packages, antepartum care, gynecological procedure coding, and preventive screening billing.",
          bullets: [
            "Global obstetric package billing",
            "Antepartum and postpartum care",
            "Mammography and screening billing",
            "Fertility treatment billing",
          ],
        },
      ],
    },
    {
      type: "cards",
      id: "surgical",
      eyebrow: "Surgical & Procedural",
      title: "High-Complexity Billing for High-Stakes Procedures",
      columns: 3,
      variant: "panel",
      items: [
        {
          id: "orthopedics",
          icon: "bone",
          title: "Orthopedics & Spine Surgery",
          body: "Total joint replacement, spinal fusion, sports medicine, fracture care, arthroscopy. Modifier 62, 80, assistant surgeon billing. Implant cost reporting.",
        },
        {
          id: "cardiology",
          icon: "heart-pulse",
          title: "Cardiology",
          body: "Invasive and non-invasive cardiology — cardiac cath, EP studies, echo, stress testing, remote monitoring (RPM), and heart failure management programs.",
        },
        {
          id: "neurology",
          icon: "brain",
          title: "Neurology & Neurosurgery",
          body: "EEG, EMG, nerve conduction, cranial/spinal surgery, sleep study billing, and deep brain stimulation program billing.",
        },
        {
          id: "ophthalmology",
          icon: "eye",
          title: "Ophthalmology",
          body: "Cataract surgery, glaucoma management, retinal procedures, vision therapy, and OCT diagnostic billing.",
        },
        {
          id: "general-surgery",
          icon: "scissors",
          title: "General Surgery",
          body: "Laparoscopic and open surgical procedures, hernia repair, bariatric surgery billing, and global surgical package management.",
        },
        {
          id: "anesthesiology",
          icon: "moon",
          title: "Anesthesiology",
          body: "Base unit and time unit anesthesia billing, CRNA and physician billing, MAC coding, and pain management procedure billing.",
        },
      ],
    },
    {
      type: "cards",
      id: "medical",
      eyebrow: "Medical Specialties",
      title: "Complex Medical Specialties — Billed Right",
      columns: 3,
      variant: "accent",
      items: [
        {
          id: "nephrology",
          icon: "droplets",
          title: "Nephrology",
          body: "Dialysis billing (in-center and home), ESRD monthly capitation, kidney transplant follow-up, CAPD/CCPD billing, and CKD management coding.",
        },
        {
          id: "oncology",
          icon: "flask",
          title: "Oncology & Hematology",
          body: "Chemotherapy infusion billing (96401–96549), immunotherapy, drug administration, oncology E&M, clinical trial billing, and radiation oncology.",
        },
        {
          id: "pulmonology",
          icon: "wind",
          title: "Pulmonology",
          body: "Spirometry and PFT billing, bronchoscopy coding, COPD management, sleep study billing, and critical care pulmonology coding.",
        },
        {
          id: "gastroenterology",
          icon: "scan",
          title: "Gastroenterology",
          body: "Colonoscopy and EGD billing, polyp removal coding, ERCP, liver biopsy, and capsule endoscopy — including screening vs. diagnostic billing.",
        },
        {
          id: "rheumatology",
          icon: "syringe",
          title: "Rheumatology",
          body: "Joint injection billing, infusion therapy for biologics, autoimmune disease management coding, and documentation support.",
        },
        {
          id: "endocrinology",
          icon: "activity",
          title: "Endocrinology",
          body: "Diabetes management billing, thyroid procedure coding, insulin pump (CSII), continuous glucose monitoring (CGM), and RPM billing.",
        },
        {
          id: "pain-management",
          icon: "pill",
          title: "Pain Management",
          body: "Epidural injection billing, nerve block coding, spinal cord stimulator, fluoroscopy guidance, drug testing, and controlled substance compliance billing.",
        },
        {
          id: "infectious-disease",
          icon: "thermometer",
          title: "Infectious Disease",
          body: "HIV/AIDS management, antimicrobial stewardship, complex antibiotic infusion billing, hospital consultation coding.",
        },
        {
          id: "dermatology",
          icon: "microscope",
          title: "Dermatology",
          body: "Lesion removal coding, Mohs surgery billing, cosmetic vs. medically necessary distinction, biopsy coding, and phototherapy billing.",
        },
      ],
    },
    {
      type: "cards",
      id: "behavioral-health",
      eyebrow: "Behavioral Health",
      title: "Mental Health & Substance Use — A Specialty That Demands Precision",
      lead: "Behavioral health billing has unique parity requirements, licensure considerations, and payer-specific authorization rules. Our behavioral health billing team navigates all of it.",
      columns: 2,
      variant: "default",
      items: [
        {
          id: "psychiatry",
          icon: "smile",
          title: "Psychiatry & Psychology",
          body: "Psychiatric evaluation coding, psychotherapy time-based billing, neuropsychological testing, and inpatient psychiatric billing.",
        },
        {
          id: "counseling",
          icon: "hand-heart",
          title: "Counseling & Therapy",
          body: "Individual, group, and family therapy billing for LCSWs, LPCs, MFTs, and licensed counselors with parity law compliance.",
        },
        {
          id: "substance-use",
          icon: "pill",
          title: "Substance Use Treatment",
          body: "OTP/MAT billing, ASAM level of care coding, methadone/buprenorphine billing, IOP and residential treatment, and SBIRT coding.",
        },
        {
          id: "aba-therapy",
          icon: "baby",
          title: "ABA Therapy",
          body: "ABA therapy billing for autism spectrum disorder — protocol modification, technician supervision, and Medicaid ABA waiver program billing.",
        },
      ],
    },
    {
      type: "cards",
      id: "diagnostic",
      eyebrow: "Diagnostic & Post-Acute",
      title: "Diagnostic Services & Long-Term Care",
      columns: 3,
      variant: "default",
      items: [
        {
          id: "radiology",
          icon: "radio",
          title: "Radiology & Imaging",
          body: "Professional and technical component billing, diagnostic and interventional radiology, MRI/CT/X-ray, PET scan, and teleradiology billing.",
        },
        {
          id: "pathology-labs",
          icon: "microscope",
          title: "Pathology & Clinical Laboratory",
          body: "Clinical lab billing with CLIA compliance, anatomic pathology coding, molecular diagnostics, genetic testing, and PAMA payment rules.",
        },
        {
          id: "physical-therapy",
          icon: "footprints",
          title: "Physical & Occupational Therapy",
          body: "Therapy billing with KX modifier management, functional limitation reporting, Medicare therapy cap tracking, and group vs. individual billing compliance.",
        },
        {
          id: "emergency-medicine",
          icon: "ambulance",
          title: "Emergency Medicine",
          body: "ED E&M level assignment (99281–99285), critical care coding, trauma activation billing, and No Surprises Act compliance management.",
        },
        {
          id: "hospital-medicine",
          icon: "hospital",
          title: "Hospital Medicine",
          body: "Admission, subsequent, and discharge E&M coding, critical care billing, observation services, and hospitalist group billing.",
        },
        {
          id: "home-health",
          icon: "home",
          title: "Home Health & Hospice",
          body: "PDGM episode billing, OASIS coding, home health certification, hospice benefit period billing, and routine home vs. continuous care coding.",
        },
        {
          id: "skilled-nursing",
          icon: "building",
          title: "Skilled Nursing (SNF)",
          body: "PDPM billing, Part A SNF billing, Part B ancillary services, attending physician visits, and Medicare triple-check audit preparation.",
        },
        {
          id: "telehealth",
          icon: "globe",
          title: "Telehealth / Virtual Care",
          body: "Telehealth billing across all payers, place of service compliance, audio-only vs. video coding, RPM/PCM billing, and interstate telehealth support.",
        },
        {
          id: "speech-therapy",
          icon: "message",
          title: "Speech-Language Pathology",
          body: "SLP billing for dysphagia, communication disorders, voice therapy, cognitive rehabilitation, and AAC device billing through Medicaid and commercial payers.",
        },
      ],
    },
    {
      type: "tiles",
      id: "all-specialties",
      title: "Every Specialty. Without Exception.",
      lead: "Don't see yours? If healthcare providers bill for it, we bill it.",
      items: [
        { icon: "stethoscope", label: "Family Medicine" },
        { icon: "heart-pulse", label: "Cardiology" },
        { icon: "bone", label: "Orthopedics" },
        { icon: "brain", label: "Neurology" },
        { icon: "droplets", label: "Nephrology" },
        { icon: "flask", label: "Oncology" },
        { icon: "scan", label: "Gastroenterology" },
        { icon: "wind", label: "Pulmonology" },
        { icon: "syringe", label: "Rheumatology" },
        { icon: "gauge", label: "Endocrinology" },
        { icon: "eye", label: "Ophthalmology" },
        { icon: "flower", label: "OB/GYN" },
        { icon: "baby", label: "Pediatrics" },
        { icon: "smile", label: "Psychiatry" },
        { icon: "radio", label: "Radiology" },
        { icon: "microscope", label: "Pathology & Labs" },
        { icon: "moon", label: "Anesthesiology" },
        { icon: "scissors", label: "General Surgery" },
        { icon: "ambulance", label: "Emergency Medicine" },
        { icon: "hospital", label: "Hospital Medicine" },
        { icon: "zap", label: "Urgent Care" },
        { icon: "activity", label: "Physical Therapy" },
        { icon: "message", label: "Speech Therapy" },
        { icon: "hand-heart", label: "Occupational Therapy" },
        { icon: "smile", label: "Oral Surgery" },
        { icon: "ear", label: "ENT" },
        { icon: "footprints", label: "Podiatry" },
        { icon: "pill", label: "Pain Management" },
        { icon: "thermometer", label: "Infectious Disease" },
        { icon: "home", label: "Home Health" },
        { icon: "heart", label: "Hospice Care" },
        { icon: "building", label: "Skilled Nursing" },
        { icon: "puzzle", label: "ABA Therapy" },
        { icon: "refresh", label: "Substance Use" },
        { icon: "sparkles", label: "Dermatology" },
        { icon: "video", label: "Telehealth" },
        { icon: "trophy", label: "Sports Medicine" },
        { icon: "heart-pulse", label: "Vascular Surgery" },
        { icon: "users", label: "Multispecialty Groups" },
        { icon: "globe", label: "Concierge Medicine" },
      ],
    },
  ],
  cta: {
    title: "Your Specialty. Our Expertise. More Revenue.",
    lead: "Tell us your specialty and we'll show you exactly how we've increased collections for practices just like yours — with real numbers, not promises.",
    button: { label: "Request a Specialty-Specific Demo", href: routes.freeAudit },
  },
};
