import {
  Activity,
  AlertTriangle,
  Ambulance,
  ArrowRight,
  Baby,
  BadgeCheck,
  BarChart3,
  Bell,
  BookOpen,
  Bone,
  Brain,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  Car,
  CheckCircle2,
  ChevronDown,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cpu,
  Droplets,
  Ear,
  Eye,
  FileCheck,
  FileSearch,
  FileText,
  FlaskConical,
  Flower2,
  Footprints,
  Gauge,
  Globe,
  HandHeart,
  HardHat,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Landmark,
  Layers,
  LineChart,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Mic,
  Microscope,
  Moon,
  Newspaper,
  Phone,
  PieChart,
  Pill,
  Puzzle,
  Radio,
  Receipt,
  RefreshCw,
  Repeat,
  Scale,
  ScanLine,
  Scissors,
  Search,
  Send,
  Shield,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Syringe,
  Thermometer,
  Timer,
  TrendingDown,
  TrendingUp,
  Trophy,
  User,
  Users,
  Video,
  Wallet,
  Wind,
  X,
  Zap,
  type LucideProps,
} from "lucide-react";

/**
 * Single icon registry. Content files reference icons by name so that the
 * content layer stays serialisable and only the icons actually used ship.
 */
export const icons = {
  activity: Activity,
  alert: AlertTriangle,
  ambulance: Ambulance,
  "arrow-right": ArrowRight,
  baby: Baby,
  "badge-check": BadgeCheck,
  "bar-chart": BarChart3,
  bell: Bell,
  book: BookOpen,
  bone: Bone,
  brain: Brain,
  briefcase: Briefcase,
  building: Building2,
  calculator: Calculator,
  calendar: Calendar,
  car: Car,
  check: CheckCircle2,
  "chevron-down": ChevronDown,
  dollar: CircleDollarSign,
  "clipboard-check": ClipboardCheck,
  clipboard: ClipboardList,
  clock: Clock,
  cpu: Cpu,
  droplets: Droplets,
  ear: Ear,
  eye: Eye,
  "file-check": FileCheck,
  "file-search": FileSearch,
  file: FileText,
  flask: FlaskConical,
  flower: Flower2,
  footprints: Footprints,
  gauge: Gauge,
  globe: Globe,
  "hand-heart": HandHeart,
  "hard-hat": HardHat,
  heart: Heart,
  "heart-pulse": HeartPulse,
  home: Home,
  hospital: Hospital,
  landmark: Landmark,
  layers: Layers,
  "line-chart": LineChart,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  message: MessageSquare,
  mic: Mic,
  microscope: Microscope,
  moon: Moon,
  newspaper: Newspaper,
  phone: Phone,
  "pie-chart": PieChart,
  pill: Pill,
  puzzle: Puzzle,
  radio: Radio,
  receipt: Receipt,
  refresh: RefreshCw,
  repeat: Repeat,
  scale: Scale,
  scan: ScanLine,
  scissors: Scissors,
  search: Search,
  send: Send,
  shield: Shield,
  "shield-check": ShieldCheck,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  syringe: Syringe,
  thermometer: Thermometer,
  timer: Timer,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  trophy: Trophy,
  user: User,
  users: Users,
  video: Video,
  wallet: Wallet,
  wind: Wind,
  x: X,
  zap: Zap,
} as const;

export type IconName = keyof typeof icons;

interface IconProps extends LucideProps {
  name: IconName;
}

export function Icon({ name, ...props }: IconProps) {
  const Cmp = icons[name];
  return <Cmp aria-hidden="true" focusable="false" {...props} />;
}
